import { RoleConfig, ProjectRole, CueType } from "@/types";

export const ROLES: Record<ProjectRole, RoleConfig> = {
  STAGE_MANAGER: {
    id: "STAGE_MANAGER",
    label: "Stage Manager",
    icon: "◆",
    color: "#E8C547",
    visibleCueTypes: ["LIGHT", "SOUND", "PROPS", "SET", "BLOCKING", "PROJECTION", "FLY", "SPOT"],
    showAllDialogue: true,
    showStageDirections: true,
    hasCuePanel: false,
  },
  DIRECTOR: {
    id: "DIRECTOR",
    label: "Director",
    icon: "✦",
    color: "#F5F5F5",
    visibleCueTypes: ["LIGHT", "SOUND", "PROPS", "SET", "BLOCKING", "PROJECTION"],
    showAllDialogue: true,
    showStageDirections: true,
    hasCuePanel: false,
  },
  ACTOR: {
    id: "ACTOR",
    label: "Actor",
    icon: "◎",
    color: "#F5F5F5",
    visibleCueTypes: ["BLOCKING"],
    showAllDialogue: true,
    showStageDirections: true,
    hasCuePanel: false,
  },
  LIGHTING: {
    id: "LIGHTING",
    label: "Lighting",
    icon: "☀",
    color: "#47B8E8",
    visibleCueTypes: ["LIGHT"],
    showAllDialogue: true,
    showStageDirections: true,
    hasCuePanel: true,
  },
  SOUND: {
    id: "SOUND",
    label: "Sound",
    icon: "♫",
    color: "#E87847",
    visibleCueTypes: ["SOUND"],
    showAllDialogue: true,
    showStageDirections: true,
    hasCuePanel: true,
  },
  SET_DESIGN: {
    id: "SET_DESIGN",
    label: "Set Design",
    icon: "▧",
    color: "#7BE847",
    visibleCueTypes: ["SET"],
    showAllDialogue: false,
    showStageDirections: true,
    hasCuePanel: true,
  },
  PROPS: {
    id: "PROPS",
    label: "Props",
    icon: "✦",
    color: "#C847E8",
    visibleCueTypes: ["PROPS"],
    showAllDialogue: false,
    showStageDirections: true,
    hasCuePanel: true,
  },
  VIEWER: {
    id: "VIEWER",
    label: "Viewer",
    icon: "◌",
    color: "#888",
    visibleCueTypes: [],
    showAllDialogue: true,
    showStageDirections: true,
    hasCuePanel: false,
  },
};

export const ROLE_LIST = Object.values(ROLES);
